# Site settings
title: ludak.me
email: ludak@ludak.me
description: > # this means to ignore newlines until "baseurl:"
  ludak.me is an account of thoughts, and events I find interesting.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ludak.me" # the base hostname & protocol for your site
twitter_username: _NareshPS
github_username:  NareshPS

# Build settings
markdown: kramdown
