# Plugins
gems:               ['jekyll-paginate']

# Dependencies
markdown:            redcarpet

# Pagination
paginate: 1

# Setup
title:               ludak.me
tagline:             'ludak.me'
description:         'ludak.me is an account of thoughts, and events that I find interesting. Find me on twitter <a href="https://twitter.com/_NareshPS" target="_blank">@_NareshPS</a>.'
url:                 http://ludak.me
baseurl:             /

# About/contact
author:
  name:              Naresh Singh
  url:               https://twitter.com/_NareshPS

# Custom vars
version:             1.0.0

#emoticon mapping
#code source: http://www.alt-codes.net/smiley_alt_codes.php
emoticon_mapping:
  - name: ':)'
    unicode_name: '&#x1F642;'
  - name: ':P'
    unicode_name: '&#x1F61D;'
  - name: ':('
    unicode_name: '&#x1F641;'
  - name: ':O'
    unicode_name: '&#x1F62F;'
  - name: ':D'
    unicode_name: '&#x1F606;'
