# Plugins
gems:               ['jekyll-paginate', 'gemoji']

# Dependencies
markdown:            redcarpet

# Pagination
paginate: 1

# Setup
title:               ludak.me
tagline:             'ludak.me'
description:         'ludak.me is an account of thoughts, and events that I find interesting. Find me on twitter <a href="https://twitter.com/_NareshPS" target="_blank">@_NareshPS</a>.'
url:                 http://ludak.me
baseurl:             /

# About/contact
author:
  name:              Naresh Singh
  url:               https://twitter.com/_NareshPS

# Custom vars
version:             1.0.0

#gemoji
emoji_dir:           ./images/emoji

#emoji mapping
emoji_mapping:
  - simple_name: ':)'
    emoji_name: ':smile:'
  - simple_name: ':P'
    emoji_name: ':stuck_out_tongue_closed_eyes:'
