source "https://rubygems.org"

# web framework
gem 'jekyll'

# image related
gem 'rmagick', '~> 2.15.0'
gem 'paperclip', :git => 'git://github.com/thoughtbot/paperclip.git'

# required by jekyll
gem 'redcarpet'
gem 'jekyll-paginate'

# gets image sizes
gem 'fastimage'

# emoji
gem 'emoji_for_jekyll'
